#include "actions.h"
#include "config.h"
#include "red.h"

/*
    ENV VARS:
      RED_DONT_SPAWN_CLIENT:
          Force not spawing in as a client.
          Currently using it to use my other gpu thats not used by anything
          while in a wayland compositor. Outputting directly on the monitor
          connected.

      RED_SOCKET:
          Set by the display server.
          Pointing to the unix socked path used by the ipc.
      RED_PARENT_WAYLAND_DISPLAY:
          Set by the display server.
          Pointing to the parent display server that red is running in.

     CURSOR:
       Cursor image is set in the `red_cursor.c` file.
       Currently it is generated by gimp .c format export with default options.
         By default gimp set's the exported struct as static, remove that!

       The only thing to watch out for is the size cap, if you keep it within
         0 to 120 px you are probably fine, above that it varies
         by cursor planes of the gpu.

       In the config below `center_cursor_hotspot` can be set if you
         want your hotspot to be in the center of the image exported.
*/

redconfig cfg = (redconfig){
    /*
      /dev/dri/card0, /dev/dri/card1

      setting to `auto` will find the first card in /dev/dri
    */
    .dri_dev = "auto",
    /*
      /dev/dri/renderD128, /dev/dri/renderD129

      setting to `auto` will find the first render node in /dev/dri
      starting at 128 searching forward
    */
    .dri_render_dev = "auto",

    // windows will be scaled by this factor
    .screen_scale = 2,

    .kb_repeat_delay = 300,
    .kb_repeat_rate  = 50,

    .xkb_rules   = "",
    .xkb_model   = "",
    .xkb_layout  = "us,us",
    .xkb_variant = ",dvorak",
    .xkb_options = "grp:win_space_toggle, ctrl:swap_ralt_rctl",

    // center the cursor hotspot in the middle of the
    // exported image in red_cursor.c
    .center_cursor_hotspot = false,

    // time in miliseconds that the cursor
    // will get hidden after the last motion event
    .cursor_autohide_time = 2000,

    // initially selected bind preset
    // can be changed at runtime with RED_ACTION_SELECT_BIND_PRESET
    .sel_bind_preset = 0,

    // disable/enable animations
    // currently only one is the `on window focus change` one
    .animations = true,

    // duration of the focus change animation in miliseconds
    .animation_focus_change_duration = 200,

    // enable/disable Wind*ws *like* autoscroll.
    // click with middle mouse button, then move pointer
    // up and down, deppending on the distance moved - from the initial
    // click point - the more scrolling will happen.
    .autoscroll = true,

    // scale up the delay between scroll events on autoscroll.
    // 1 would keep it the same, 0 will make the delay 0, 2 and up will
    // add more delay, 0.5 will half the delay.
    // aka:
    // closer to 0 faster scrolling, closer to 1 slower scrolling
    .autoscroll_scale = 0.2,

    // if you want the autoscroll scrolling to get faster exponentially
    // set this to > 1.
    .autoscroll_expo = 16,

    // clang-format off
    // bind presets are a way to change your binds at runtime
    BIND_PRESETS(
      // Binds that use the shift mod, should change the
      // key - if it is a char (a - Z) - to uppercase.
      //
      // key: name of a libinput keysym
      // mods: bitmask of ORed RED_MOD_*
      // action & action_len: set with the `A` macro, which takes a list of RED_ACTION_*
      // wl_client: if true bind will only work if red is spawned as a client
      // not_repeated: set if you want bind to not be repeated when held (by default all are repeated)
      {BINDS(
          /* SERVER CONTROL */
          {
            .wl_client = true,
            .key = "F4",
            .mods = RED_MOD_NO_MODS,
            A( RED_ACTION_QUIT )
          },
          {
            .key = "Q",
            .mods = RED_MOD_SUPER | RED_MOD_ALT | RED_MOD_CTRL | RED_MOD_SHIFT,
            A( RED_ACTION_QUIT )
          },

          /* TOPLEVEL CONTROL */
          {
            .key = "Q",
            .mods = RED_MOD_SUPER | RED_MOD_SHIFT,
            A( RED_ACTION_CLOSE )
          },
          {
            .key = "k",
            .mods = RED_MOD_SUPER,
            A( RED_ACTION_FOCUS_PREV )
          },
          {
            .key = "j",
            .mods = RED_MOD_SUPER,
            A( RED_ACTION_FOCUS_NEXT )
          },
          {
            .key = "Tab",
            .mods = RED_MOD_ALT,
            A( RED_ACTION_FOCUS_LAST )
          },
          { .key = "1", .mods = RED_MOD_SUPER, A( RED_ACTION_FOCUS_N, "0" ) },
          { .key = "2", .mods = RED_MOD_SUPER, A( RED_ACTION_FOCUS_N, "1" ) },
          { .key = "3", .mods = RED_MOD_SUPER, A( RED_ACTION_FOCUS_N, "2" ) },
          {
            .key = "semicolon",
            .mods = RED_MOD_SUPER,
            A( RED_ACTION_OVERLAY_SURFACE )
          },

          /* SPAWNERS */
          {
            .key = "Return",
            .mods = RED_MOD_SUPER,
            A( RED_ACTION_SPAWN, "foot" )
          },
          {
            .key = "r",
            .mods = RED_MOD_SUPER,
            .not_repeated = true,
            A( RED_ACTION_SPAWN, "fuzzel" )
          },
          {
            .key = "grave",
            .mods = RED_MOD_SUPER,
            A( RED_ACTION_SPAWN, "bash", "-c", "qs -c rt_switcher ipc call main toggle")
          },



          {
            .key = "R",
            .mods = RED_MOD_SUPER | RED_MOD_SHIFT,
            A( RED_ACTION_STOP_RENDERER )
          },
          {
            .key = "I",
            .mods = RED_MOD_SUPER | RED_MOD_SHIFT,
            A( RED_ACTION_CAPTURE_FOCUS )
          },
          {
            .key = "F8",
            .mods = RED_MOD_SUPER | RED_MOD_SHIFT,
            A( RED_ACTION_SELECT_BIND_PRESET, "1" )
          },
          {
            .key = "d",
            .mods = RED_MOD_SUPER,
            A( RED_ACTION_DEBUG )
          },
      )},

      {BINDS(
          {
            .key = "F8",
            .mods = RED_MOD_SUPER | RED_MOD_SHIFT,
            A( RED_ACTION_SELECT_BIND_PRESET, "0" )
          },
      )},
    )

    AUTO_START(
        PROG("bash", "-c", "xwayland-satellite :1"),
        PROG("bash", "-c", "qs -c rt_switcher"),
    )

    ENV(
        {"DISPLAY", ":1"},
        {"XDG_CURRENT_DESKTOP", "red"},
        {"XDG_SESSION_DESKTOP", "red"},
        {"XDG_SESSION_TYPE", "wayland"},
    )

    // name -> libinput name, can be set to `*` to set to all devices
    // speed -> val between -1 and 1. -1 being the slowest
    // flat_profile -> 0 for adaptive, 1 for flat
    MOUSES(
      {
        .name = "crolbar YUKI",
        .speed = 1.0,
        .flat_profile = 0,
      },
      {
        .name = "*",
        .speed = -0.4,
        .flat_profile = 0,
      }
    )
    // clang-format on
};
